#!/usr/bin/env node

const { Logger } = require('../nlogs/dist')
const [,,cmd, ...args] = process.argv

const logger = new Logger('nlogs bin', {
    allowed: {
        console: true,
        elasticsearch: false,
        file: false
    }
})

if (cmd === 'config') {
    logger.dir(require('../nlogs/dist/config'), 10)
} else if (['log', 'show', 'write', 'send'].includes(cmd)) {
    logger.info(...args, Logger[['write', 'send'].includes(cmd) ? cmd : 'show'](true))
} else {
    const fs = require('fs')
    const path = require('path')
    const nlogsDir = path.join(__dirname, '..', 'nlogs', 'package.json')
    const pkg = fs.readFileSync(nlogsDir)
    logger.info('nlogs version:', pkg.version)
}
