#!/usr/bin/env node

const { Logger } = require('../nlogs/dist')
const [,,cmd, ...args] = process.argv

const logger = new Logger('nlogs bin', {
    allowed: {
        console: true,
        elasticsearch: false,
        file: false
    }
})

logger.category.allow()

if (cmd === 'config') {
    logger.dir(require('../nlogs/dist/config'), 10)
} else if (['log', 'show', 'write', 'send'].includes(cmd)) {
    logger.debug(...args, Logger.allowed({
        console: true,
        file: cmd.includes('write'),
        elasticsearch: cmd.includes('send')
    }))
} else {
    const fs = require('fs')
    const path = require('path')
    const nlogsDir = path.join(__dirname, '..', 'nlogs', 'package.json')
    const pkg = JSON.parse(fs.readFileSync(nlogsDir, 'utf-8'))
    logger.info('nlogs version:', Logger.highlight(pkg.version))
}
