export const IS_MESSAGE = Symbol('nlogs(is message)')
export const IS_META = Symbol('nlogs(is meta)')

export const TIME = Symbol('nlogs(message:time)')
export const HIGHLIGHT = Symbol('nlogs(message:highlight)')
export const STACKTRACE = Symbol('nlogs(message:stacktrace)')
export const DATETIME = Symbol('nlogs(message:datetime)')

export const PROJECT = Symbol('nlogs(meta:project)')
export const SERVICE = Symbol('nlogs(meta:service)')
export const CATEGORY = Symbol('nlogs(meta:category)')
export const LEVEL = Symbol('nlogs(meta:level)')
export const TRACE_ID = Symbol('nlogs(meta:traceId)')
export const DEPTH = Symbol('nlogs(meta:depth)')
export const INDEX = Symbol('nlogs(meta:index)')
export const TIMESTAMP = Symbol('nlogs(meta:timestamp)')
export const ALLOWED = Symbol('nlogs(meta:allowed)')
export const SHOW = Symbol('nlogs(meta:show)')
export const WRITE = Symbol('nlogs(meta:write)')
export const SEND = Symbol('nlogs(meta:send)')
export const META = Symbol('nlogs(meta:object)')
export const MODULE = Symbol('nlogs(meta:module)')
