name: "SYNC: dependencies with master"


on:
  push:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bump-version"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          ref: dependencies

      - name: fetch
        run: git fetch

      - name: merge master
        run: git merge origin/master --no-edit

      - name: push into dependencies
        run: git push origin dependencies